platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'TTBasicProject' do
  pod "AFNetworking", '~> 3.0.0'
  pod 'SDWebImage', '~>3.8'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'DZNEmptyDataSet'
  pod 'IQKeyboardManager'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
  pod 'Masonry'
end
