platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'TTBasicProject' do
  pod "AFNetworking", "~> 3.0"
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'SVProgressHUD'
  pod 'DZNEmptyDataSet'
  pod 'IQKeyboardManager'
  pod 'UITableView+FDTemplateLayoutCell_Bell', '~> 1.5.0'
end
